spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
server:
  port: 8081